#!/usr/bin/env bash
set -euo pipefail

echo "fmt..."
cargo fmt --all -- --check

echo "clippy..."
cargo clippy --all-targets -- -D warnings -A dead_code

echo "test..."
cargo test --quiet

chmod +x .githooks/pre-commit
